# Generated by Django 4.1.5 on 2023-02-22 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmitCase_ClinicalSheet', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('ICP', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('MedicationChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('InitialSheet', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('TPRChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('VitalChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('LOS_StayChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('CaseSheets_OtheDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClaimManagement_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
