# Generated by Django 4.1.5 on 2023-02-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0002_claimmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmanagement',
            name='AnaesthesiaNotes',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='BTSticker',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='Biochemistry',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='BloodTransfusion',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='CaseNumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthLinkCaseNumber_caseNumber', to='PreAuth.preauthlinkcasenumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='CrossMatchReport',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='DeathCertificate',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='DischargeType',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='Microbiology',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='MortalityAudit',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='OT_ProcedureSheets',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='OtherDocuments',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/OtherDoc'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='Pathology',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='Radiology',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='SerologyInvestigation',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test'),
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='Status',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='dischargeDate',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
