# Generated by Django 4.1.5 on 2023-02-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0003_claimmanagement_anaesthesianotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmanagement',
            name='CaseNumberID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthLinkCaseNumber_caseNumber', to='PreAuth.preauthlinkcasenumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimmanagement',
            name='CaseNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
