# Generated by Django 4.1.5 on 2023-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0006_remove_claimradiologydocument_claimmanagementid'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmanagement',
            name='Radiology',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports'),
        ),
    ]
