# Generated by Django 4.1.5 on 2023-02-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0007_claimmanagement_radiology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimRadiologyDocument',
        ),
        migrations.AddField(
            model_name='claimmanagement',
            name='DischargeSummaryDocument',
            field=models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary'),
        ),
    ]
