# Generated by Django 4.1.5 on 2023-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0009_dumpexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='ActualClaimSubmittedDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ActualRegistrationDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='AdmissionDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimSubmittedDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='DeathDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='DischargeDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='IPRegistrationDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthApproveDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthRejectedDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='SurgeryDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
