# Generated by Django 4.1.5 on 2023-02-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0014_preauthdocument_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='CaseNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
