# Generated by Django 4.1.5 on 2023-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0015_alter_dumpexcel_caseno_alter_dumpexcel_claimno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='FamilyId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='NHPMId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PatientDistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='RegistrationNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
