# Generated by Django 4.1.5 on 2023-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0016_alter_dumpexcel_familyid_alter_dumpexcel_nhpmid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='CategoryDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='Gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
