# Generated by Django 4.1.5 on 2023-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0018_alter_dumpexcel_casestatus_alter_dumpexcel_casetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='AssignedFlag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='AssignedGroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='AssignedUser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='CPDApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='IPNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthApproveDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthRejectedDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
