# Generated by Django 4.1.5 on 2023-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0020_alter_dumpexcel_actualclaimsubmitteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='CPDApprovedAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimApprovedAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimInitaiatedAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthApprovedAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
