# Generated by Django 4.1.5 on 2023-02-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0021_alter_dumpexcel_cpdapprovedamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='CPDApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='ClaimInitaiatedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='PreauthApprovedAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
