# Generated by Django 4.1.5 on 2023-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0022_alter_dumpexcel_cpdapprovedamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpexcel',
            name='ProcedureDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
