# Generated by Django 4.1.5 on 2023-02-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreAuth', '0024_alter_dumpexcel_proceduredetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShapeFile_path', models.FilePathField(path=pathlib.PureWindowsPath('D:/Claim Assurance/media/ShapeFIles'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapeFiles_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
