# Generated by Django 4.1.5 on 2023-02-27 10:42

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0025_shapefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefiles',
            name='ShapeFile_path',
            field=models.FilePathField(max_length=255, path=pathlib.PureWindowsPath('D:/Claim Assurance/media/ShapeFIles')),
        ),
    ]
