# Generated by Django 4.1.5 on 2023-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0026_alter_shapefiles_shapefile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefiles',
            name='ShapeFile_path',
            field=models.FileField(blank=True, null=True, upload_to='ShapeFIles'),
        ),
    ]
