# Generated by Django 4.1.5 on 2023-02-27 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreAuth', '0027_alter_shapefiles_shapefile_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefiles',
            name='ShapeFile_path',
        ),
        migrations.AddField(
            model_name='shapefiles',
            name='folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shapefiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shape_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
