# Generated by Django 4.1.5 on 2023-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0028_remove_shapefiles_shapefile_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapefiles',
            old_name='folder_path',
            new_name='folder_name',
        ),
    ]
