# Generated by Django 4.1.5 on 2023-03-06 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreAuth', '0030_remove_claimmanagement_casenumberid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='PreAuthDocuments/Enhancement_Documents')),
                ('PreAuthID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthEnhancement_PreAuthDocument', to='PreAuth.preauthdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthEnhancement_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
