# Generated by Django 4.1.5 on 2023-03-01 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PreAuth', '0030_remove_claimmanagement_casenumberid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNo', models.CharField(blank=True, max_length=255, null=True)),
                ('ClaimNo', models.CharField(blank=True, max_length=255, null=True)),
                ('RegistrationNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('NHPMId', models.CharField(blank=True, max_length=255, null=True)),
                ('FamilyId', models.CharField(blank=True, max_length=255, null=True)),
                ('PatientDistrict', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
                ('Age', models.IntegerField()),
                ('CategoryDetails', models.CharField(blank=True, max_length=255, null=True)),
                ('ProcedureDetails', models.TextField(blank=True, max_length=255, null=True)),
                ('CaseType', models.CharField(blank=True, max_length=255, null=True)),
                ('CaseStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('HospitalName', models.CharField(blank=True, max_length=255, null=True)),
                ('HospitalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('HospitalDistrict', models.CharField(blank=True, max_length=255, null=True)),
                ('PreauthAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('ClaimInitaiatedAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('CPDApprovedAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('ClaimApprovedAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignedFlag', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignedUser', models.CharField(blank=True, max_length=255, null=True)),
                ('AssignedGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('IPNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('PreauthApprovedAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('IPRegistrationDate', models.CharField(blank=True, max_length=255, null=True)),
                ('PreauthApproveDate', models.CharField(blank=True, max_length=255, null=True)),
                ('PreauthRejectedDate', models.CharField(blank=True, max_length=255, null=True)),
                ('SurgeryDate', models.CharField(blank=True, max_length=255, null=True)),
                ('DeathDate', models.CharField(blank=True, max_length=255, null=True)),
                ('DischargeDate', models.CharField(blank=True, max_length=255, null=True)),
                ('ClaimSubmittedDate', models.CharField(blank=True, max_length=255, null=True)),
                ('ActualClaimSubmittedDate', models.CharField(blank=True, max_length=255, null=True)),
                ('AdmissionDate', models.CharField(blank=True, max_length=255, null=True)),
                ('PreauthDate', models.CharField(blank=True, max_length=255, null=True)),
                ('ActualRegistrationDate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('AdmitCase_ClinicalSheet', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('ICP', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('MedicationChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('InitialSheet', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('TPRChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('VitalChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('LOS_StayChart', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('CaseSheets_OtheDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/CaseSheet')),
                ('Microbiology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('Biochemistry', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('Pathology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('SerologyInvestigation', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('Radiology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('OT_ProcedureSheets', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('AnaesthesiaNotes', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('dischargeDate', models.DateTimeField()),
                ('DischargeType', models.CharField(max_length=255)),
                ('DischargeSummaryDocument', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('MortalityAudit', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('DeathCertificate', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('BloodTransfusion', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('BTSticker', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('CrossMatchReport', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/OtherDoc')),
                ('Status', models.CharField(max_length=255)),
                ('CaseNumberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthLinkCaseNumber_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClaimManagement_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
