# Generated by Django 4.1.5 on 2023-03-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0031_preauthenhancement'),
        ('ClaimManagement', '0002_casesheet_delete_claimmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='CaseNumberID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PreAuthLinkCaseNumber_caseNumber', to='PreAuth.preauthlinkcasenumber'),
        ),
    ]
