# Generated by Django 4.1.5 on 2023-03-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreAuth', '0031_preauthenhancement'),
        ('ClaimManagement', '0003_alter_casesheet_casenumberid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesheet',
            old_name='CaseSheets_OtheDocuments',
            new_name='OtherDocuments',
        ),
        migrations.AlterField(
            model_name='casesheet',
            name='CaseNumberID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CaseSheet_caseNumber', to='PreAuth.preauthlinkcasenumber'),
        ),
        migrations.AlterField(
            model_name='casesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CaseSheet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Microbiology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('Biochemistry', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('Pathology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('SerologyInvestigation', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('OtheDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Lab Test')),
                ('CaseNumberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LabTest_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabTest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
