# Generated by Django 4.1.5 on 2023-03-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0004_rename_casesheets_othedocuments_casesheet_otherdocuments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='OtheDocuments',
            new_name='OtherDocuments',
        ),
    ]
