# Generated by Django 4.1.5 on 2023-03-08 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0031_preauthenhancement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClaimManagement', '0005_rename_othedocuments_labtest_otherdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Radiology', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('OT_ProcedureSheets', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('AnaesthesiaNotes', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Reports')),
                ('CaseNumberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Reports_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
