# Generated by Django 4.1.5 on 2023-03-09 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PreAuth', '0031_preauthenhancement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClaimManagement', '0006_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dischargeDate', models.DateTimeField()),
                ('DischargeType', models.CharField(max_length=255)),
                ('DischargeSummaryDocument', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('CaseNumberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DischargeSummary_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DischargeSummary_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeathSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MortalityAudit', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('DeathCertificate', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Death Summary')),
                ('CaseNumberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DeathSummary_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeathSummary_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodTransfusion', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('BTSticker', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('CrossMatchReport', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/Blood Documents')),
                ('OtherDocuments', models.FileField(blank=True, null=True, upload_to='ClaimDocuments/OtherDoc')),
                ('CaseNumberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BloodDocuments_caseNumber', to='PreAuth.preauthlinkcasenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BloodDocuments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
