# Generated by Django 4.1.5 on 2023-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0008_mpclaimpaidexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='CPD_Processing_Time',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
