# Generated by Django 4.1.5 on 2023-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0011_alter_mpclaimpaidexcel_cpd_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='Claim_approval_remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='Claim_rejection_remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='PreAuth_approval_remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='PreAuth_rejection_remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='Preauth_Pending_Updated_Remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='Procedure',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='Revoked_Remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
