# Generated by Django 4.1.5 on 2023-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0012_alter_mpclaimpaidexcel_claim_approval_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpclaimpaidexcel',
            name='id',
        ),
        migrations.AlterField(
            model_name='mpclaimpaidexcel',
            name='CaseNumber',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
