# Generated by Django 4.1.5 on 2023-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimManagement', '0013_remove_mpclaimpaidexcel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpexcel',
            name='id',
        ),
        migrations.AlterField(
            model_name='dumpexcel',
            name='CaseNo',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
